server:
  port: 8087
spring:
  application:
    name: backoffice-bff
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/auth/realms/Yas
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF
            scope:
              - email
              - profile
              - roles
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://jaeger:30017
---

spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
      gateway:
        routes:
        - id: api
          uri: http://api.yas.local
          predicates:
              - Path=/api/**
          filters:
              - RewritePath=/api/(?<segment>.*), /$\{segment}
              - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
              - Path=/**
---

spring:
  config:
    activate:
      on-profile: "prod"
  cloud:
      gateway:
        routes:
          - id: api
            uri: http://product
            predicates:
                - Path=/api/product/**
            filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
          - id: nextjs
            uri: http://localhost:3000
            predicates:
                - Path=/**
